# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
		{ device = "/dev/disk/by-uuid/eaae1055-7db8-4029-9c54-6e5d08858547";
			fsType = "btrfs";
		};

	fileSystems."/boot" =
		{ device = "/dev/disk/by-uuid/FA9A-93DA";
			fsType = "vfat";
		};

	swapDevices =
		[ { device = "/dev/disk/by-uuid/ea95e294-d40f-46cc-9cfb-536bb8be85a6"; }
		];

	powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
